name: 'R-actions'
description: 'Generate NAMESPACE file for specific R package and run check'
inputs:
  buildSubDirectory:
    description: 'The path saving source code of package in repository'
    default: './'
runs:
  runs-on: ubuntu-latest
  container: ruihe864/dsp_github_workflow_env:dsp_github_workflow_env
  args:
    - ${{inputs.buildSubDirectory}}
